// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVUleTdpRr0KVQKQpA12K8-ht3MQGJUeQ',
    appId: '1:835439441759:web:6fcd7cc6c7a4af2ad228ea',
    messagingSenderId: '835439441759',
    projectId: 'little-wing-v2',
    authDomain: 'little-wing-v2.firebaseapp.com',
    databaseURL: 'https://little-wing-v2-default-rtdb.firebaseio.com',
    storageBucket: 'little-wing-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTYogP6dIJx-Z3Uu285s6_HVLpig4ck-k',
    appId: '1:835439441759:android:9f5cee39da107465d228ea',
    messagingSenderId: '835439441759',
    projectId: 'little-wing-v2',
    databaseURL: 'https://little-wing-v2-default-rtdb.firebaseio.com',
    storageBucket: 'little-wing-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx1d67S0FW6xCJsL8b5RoPUiByabDv_Kw',
    appId: '1:835439441759:ios:9e47bf03c98536e4d228ea',
    messagingSenderId: '835439441759',
    projectId: 'little-wing-v2',
    databaseURL: 'https://little-wing-v2-default-rtdb.firebaseio.com',
    storageBucket: 'little-wing-v2.firebasestorage.app',
    iosBundleId: 'com.example.dipstoreUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx1d67S0FW6xCJsL8b5RoPUiByabDv_Kw',
    appId: '1:835439441759:ios:9e47bf03c98536e4d228ea',
    messagingSenderId: '835439441759',
    projectId: 'little-wing-v2',
    databaseURL: 'https://little-wing-v2-default-rtdb.firebaseio.com',
    storageBucket: 'little-wing-v2.firebasestorage.app',
    iosBundleId: 'com.example.dipstoreUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVUleTdpRr0KVQKQpA12K8-ht3MQGJUeQ',
    appId: '1:835439441759:web:7d388a3e142cade0d228ea',
    messagingSenderId: '835439441759',
    projectId: 'little-wing-v2',
    authDomain: 'little-wing-v2.firebaseapp.com',
    databaseURL: 'https://little-wing-v2-default-rtdb.firebaseio.com',
    storageBucket: 'little-wing-v2.firebasestorage.app',
  );
}
